# Generated by Django 6.0.5 on 2026-06-09 13:59

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_seed_charities"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="effective_exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0000"),
                help_text="Canadian dollars per 1 USD applied when this donation was stored",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitestats",
            name="ca_exchange_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0000"),
                help_text="Canadian dollars per 1 USD.",
                max_digits=10,
            ),
        ),
    ]
